Traceback (most recent call last):
  File "/home/ben/miniconda3/envs/myCareerBook/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/ben/miniconda3/envs/myCareerBook/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ben/miniconda3/envs/myCareerBook/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/ben/miniconda3/envs/myCareerBook/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/home/ben/miniconda3/envs/myCareerBook/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ben/miniconda3/envs/myCareerBook/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/home/ben/miniconda3/envs/myCareerBook/lib/python3.9/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/ben/miniconda3/envs/myCareerBook/lib/python3.9/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
pd.showfield_activity
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-4-1c5d7fa183c8>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mpd[0m[0;34m.[0m[0mshowfield_activity[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/miniconda3/envs/Dimech-env/lib/python3.7/site-packages/pandas/__init__.py[0m in [0;36m__getattr__[0;34m(name)[0m
[1;32m    242[0m         [0;32mreturn[0m [0m_SparseArray[0m[0;34m[0m[0;34m[0m[0m
[1;32m    243[0m [0;34m[0m[0m
[0;32m--> 244[0;31m     [0;32mraise[0m [0mAttributeError[0m[0;34m([0m[0;34mf"module 'pandas' has no attribute '{name}'"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    245[0m [0;34m[0m[0m
[1;32m    246[0m [0;34m[0m[0m

[0;31mAttributeError[0m: module 'pandas' has no attribute 'showfield_activity'
AttributeError: module 'pandas' has no attribute 'showfield_activity'

