Traceback (most recent call last):
  File "/home/ben/miniconda3/envs/myCareerBook/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/ben/miniconda3/envs/myCareerBook/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ben/miniconda3/envs/myCareerBook/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/ben/miniconda3/envs/myCareerBook/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/home/ben/miniconda3/envs/myCareerBook/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ben/miniconda3/envs/myCareerBook/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/home/ben/miniconda3/envs/myCareerBook/lib/python3.9/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/ben/miniconda3/envs/myCareerBook/lib/python3.9/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
library(rmarkdown)
library(scholar)      # To request data from google scholar.
library(tidyverse)    # What do you do without?
library(hrbrthemes)
library(DT)
------------------

Error in library(scholar): there is no package called ‘scholar’
Traceback:

1. library(scholar)
ERROR: Error in library(scholar): there is no package called ‘scholar’


